### ISSUE TITLE
Not support Idea2017.3?

### ISSUE THREAD

**Issue by peng051410** [Emadpres/CodeTimeMachine#14]
I like your plug-in very much, but I didn't find it in the 2017 idea, is it incompatible?

**Comment by Emadpres** [comment]
It should be fine. Did you try to install it from the binary of [latest version](https://github.com/Emadpres/CodeTimeMachine/releases/tag/v1.2)? What's the error?

**Comment by peng051410** [comment]
I got error:
`-1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.reveal.codetimemachine.Commits3DView.getStringFromCommits(Commits3DView.java:938)
	at com.reveal.codetimemachine.Commits3DView.loadMainEditorWindowContent(Commits3DView.java:964)
	at com.reveal.codetimemachine.Commits3DView.access$500(Commits3DView.java:32)
	at com.reveal.codetimemachine.Commits3DView$CustomEditorTextField.createEditor(Commits3DView.java:1410)
	at com.intellij.ui.EditorTextField.c(EditorTextField.java:365)
	at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:348)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1122)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.ui.ThreeComponentsSplitter.setLastComponent(ThreeComponentsSplitter.java:434)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.a(ToolWindowsPane.java:368)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.access$400(ToolWindowsPane.java:57)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddDockedComponentCmd.run(ToolWindowsPane.java:760)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:93)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:74)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by peng051410** [comment]
An other error:
`-1
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.reveal.codetimemachine.Commits3DView.tick(Commits3DView.java:896)
	at com.reveal.codetimemachine.Commits3DView.access$000(Commits3DView.java:32)
	at com.reveal.codetimemachine.Commits3DView$1.actionPerformed(Commits3DView.java:132)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Emadpres** [comment]
Hi back,
I just installed the plugin on "IntelliJ 2017.3 Community" (yours, right?) and I don't get the error. Are you still getting the error?
By the way, If the project you get the error from is open-source, please give me the link and I will try to replicate your situation to see if I get the error or not.

**Comment by peng051410** [comment]
It works, I just reinstall it!
